Revisão
HMJussani/nodeJs pull request #1
Opened 2020-02-18 01:20 UTC by HMJussani

2020-02-18 11:03 UTC, dotenorio requested changes

2020-02-18 11:03 UTC, dotenorio commented on tutofaz/assets/js/gravar.js
> +        firebase.database().ref("Tutoriais/"+title+"/"+ interacao).set({
pq removeu o template string?

2020-02-18 11:03 UTC, dotenorio commented on tutofaz/assets/js/ler.js
> +    firebase.database().ref(`Tutoriais`).on(`child_added`, function (snapshot) {
pq template string aqui?

2020-02-18 11:32 UTC, HMJussani commented on tutofaz/assets/js/gravar.js
> +        firebase.database().ref("Tutoriais/"+title+"/"+ interacao).set({
Minha intenção é deixar o template string em todo o código, mas nesta função, depois de mudra para template string começou a gravar errado no banco - ainda não descobri o porque - volteio código para continuar funcionando.

2020-02-18 11:44 UTC, dotenorio commented on tutofaz/assets/js/gravar.js
> +        firebase.database().ref("Tutoriais/"+title+"/"+ interacao).set({
Ao que tudo indica ficaram alguns espaços extras ali, acredito que era só isso!

2020-02-18 11:53 UTC, HMJussani commented on tutofaz/assets/js/ler.js
> +    firebase.database().ref(`Tutoriais`).on(`child_added`, function (snapshot) {
A ideia é deixar tudo com template string, aqui já esta feita a mudança. Vou alterar os outros arquivos tbm e trocar os ...getElementsById(...) pelo ...querySelector(...).

2020-02-18 12:05 UTC, dotenorio commented on tutofaz/assets/js/ler.js
> +    firebase.database().ref(`Tutoriais`).on(`child_added`, function (snapshot) {
Então, use template string quando precisar mesclar string com variável, quando foi só variável ou só string é desnecessário e pode custar um pouco na performance no fim das contas!

2020-02-18 12:39 UTC, HMJussani commented on tutofaz/assets/js/gravar.js
> +        firebase.database().ref("Tutoriais/"+title+"/"+ interacao).set({
Realmente. Vou rever e atualizar!

2020-02-18 12:40 UTC, dotenorio commented on tutofaz/assets/js/gravar.js
> +        firebase.database().ref("Tutoriais/"+title+"/"+ interacao).set({
Ok, beijo gato!

2020-02-18 12:45 UTC, HMJussani commented on tutofaz/assets/js/ler.js
> +    firebase.database().ref(`Tutoriais`).on(`child_added`, function (snapshot) {
Ótima dica! Anotado!!

2020-02-19 11:13 UTC, dotenorio commented on tutofaz/assets/js/ler.js
Não cara, sem espaço aqui! kkkkkk

2020-02-19 11:43 UTC, HMJussani commented on tutofaz/assets/js/ler.js
Sr! Yes Sr!

2020-02-25 19:23 UTC, merged